messageCount: 20 #20200000
queueName: sampleQueue
exchangeName: foo.bar
routingKey: baz.bam
org:
  springframework:
    cloud:
      bindings:
        boot:
          enable: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
